### ISSUE TITLE
The "trick" to make the keyboard more power efficient

### ISSUE THREAD

**Issue by dumblob** [betrusted-io/betrusted-hardware#5]
IIRC I saw somewhere a "trick" to even further preserve power by keeping some parts of the keyboard low instead of under current.

I can't find it though now - could you point me to the relevant places (design parts if any and then the corresponding firmware code)?

Thanks!

**Comment by bunnie** [comment]
Maybe you're referring to this section?

https://github.com/betrusted-io/betrusted-ec/blob/4310e7c4ceef986580d42d3da15c089eaf5f9ded/sw/src/main.rs#L82-L98

The basic issue with the keyboard was getting it so that the pull-ups to sense the hit on a keyboard didn't bleed current into the sometimes powered-off FPGA, which was primarily accomplished by the introduction of isolation FETs (U12K on the mainboard schematic). Before the FETs were introduced some diddling about was done with tri-state drive etc. to limit the amount of time stuff was driven high due to the high leakage into the powered-off FPGA.

**Comment by dumblob** [comment]
That's exactly it! Thanks!
